version: '2'
##############
# Networking #
##############
networks:
  default:
    external:
      name: media
##############
# Containers #
##############
services:
  ###############
  # letsencrypt #
  ###############
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 443:443
      - 80:80
    volumes:
      - /path/to/letsencrypt/config:/config
    restart:
      always
    environment:
      - PUID=1000
      - PGID=1000
      - VALIDATION=http
      - EMAIL=<EMAIL ADDRESS>
      - URL=<DOMAIN>
      - SUBDOMAINS=<SUBDOMAINS>
      - TZ=America/New_York
     # - STAGING=true
  ########
  # plex #
  ########
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
      - PLEX_CLAIM=<PLEX_CLAIM_CODE>
    hostname: plex
    labels:
      - stack=media
    volumes:
      - /path/to/plex/config:/config
      - /path/to/transcode:/transcode
      - /path/to/media:/media
  ############
  # tautulli #
  ############
  tautulli:
    container_name: tautulli
    image: shiggins8/tautulli:latest
    restart: unless-stopped
    expose:
      - 8181:8181/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    hostname: tautulli
    labels:
      - stack=media
    volumes:
      - /path/to/tautulli/config:/config
      - /path/to/plex/config/Library/Logs:/logs
  ###########
  # jackett #
  ###########
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    hostname: jackett
    labels:
      - stack=media
    volumes:
      - /path/to/jackett/config:/config
      - /path/to/downloads/queue:/downloads
  ##########
  # lidarr #
  ##########
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    ports:
      - 8686:8686/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    hostname: lidarr
    labels:
      - stack=media
    volumes:
      - /path/to/lidarr/config:/config
      - /path/to/downloads:/downloads
      - /path/to/music:/music
  ########
  # ombi #
  ########
  ombi:
    container_name: ombi
    image: 	linuxserver/ombi:latest
    restart: unless-stopped
    ports:
      - 3579/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    hostname: ombi
    labels:
      - stack=media
    volumes:
      - /path/to/ombi/config:/config
  ##########
  # radarr #
  ##########
  radarr:
    container_name: radarr
    image: 	linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    hostname: radarr
    labels:
      - stack=media
    volumes:
      - /path/to/radarr/config:/config
      - /path/to/downloads:/downloads
      - /path/to/movies:/movies
  ##########
  # sonarr #
  ##########
  sonarr:
    container_name: sonarr
    image: 	linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    hostname: sonarr
    labels:
      - stack=media
    volumes:
      - /path/to/tv:/tv
      - /path/to/sonarr/config:/config
      - /path/to/downloads:/downloads
  ################
  # transmission #
  ################
  transmission:
    container_name: transmission
    image: 	linuxserver/transmission:148
    restart: unless-stopped
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
      - 9091:9091/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    hostname: transmission
    labels:
      - stack=media
    volumes:
      - /path/to/transmission/config:/config
      - /path/to/downloads:/downloads/complete
      - /path/to/downloads/incomplete:/downloads/incomplete
      - /path/to/downloads/watch:/downloads/watch
  #################
  # lazylibrarian #
  #################
  lazylibrarian:
    container_name: lazylibrarian
    image: linuxserver/lazylibrarian:latest
    restart: unless-stopped
    ports:
      - 5299:5299/tcp
    volumes:
      - /path/to/lazylibrarian/config:/config
      - /path/to/books:/books
      - /path/to/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    labels:
      - stack=media
    hostname: lazylibrarian
  #############
  # ubooquity #
  #############
  ubooquity:
    image: linuxserver/ubooquity:latest
    container_name: ubooquity
    volumes:
      - /path/to/ubooquity/config:/config
      - /path/to/books:/books
      - /path/to/comics:/comics
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    restart: unless-stopped
    labels:
      - stack=media
    hostname: ubooquity
    ports:
      - 2202:2202/tcp
      - 2203:2203/tcp
  #########
  # mylar #
  #########
  mylar:
    image: linuxserver/mylar:latest
    container_name: mylar
    volumes:
      - /path/to/mylar/config:/config
      - /path/to/comics:/comics
      - /path/to/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
    restart: unless-stopped
    hostname: mylar
    labels:
      - stack=media
    ports:
      - 8090:8090/tcp
  ####################
  # static-file-server #
  ####################
  static-file-server:
    image: halverneus/static-file-server:latest
    container_name: static-file-server
    volumes:
      - /path/to/shared/content:/content
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America\New_York
      - FOLDER=/content
    restart: unless-stopped
    hostname: static-file-server
    labels:
      - stack=media
    ports:
      - 8080/tcp
